version: '2'
networks:
  pelias:
    driver: bridge
volumes:
  libpostaldata:
    driver: local
services:
  baseimage:
    image: pelias/baseimage
    container_name: pelias_baseimage
    build: dependencies/baseimage
  whosonfirst_data:
    depends_on: [ "baseimage" ]
    image: pelias/whosonfirst_data
    container_name: pelias_whosonfirst_data
    build: data/whosonfirst
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openaddresses_data:
    depends_on: [ "baseimage" ]
    image: pelias/openaddresses_data
    container_name: pelias_openaddresses_data
    build: data/openaddresses
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openstreetmap_data:
    depends_on: [ "baseimage" ]
    image: pelias/openstreetmap_data
    container_name: pelias_openstreetmap_data
    build: data/openstreetmap
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  placeholder_data:
    depends_on: [ "baseimage" ]
    image: pelias/placeholder_data
    container_name: pelias_placeholder_data
    build: data/placeholder
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  polylines_data:
    depends_on: [ "baseimage" ]
    image: pelias/polylines_data
    container_name: pelias_polylines_data
    build: data/polylines
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  schema:
    depends_on: [ "baseimage" ]
    image: pelias/schema
    container_name: pelias_schema
    build: dependencies/schema
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
  api:
    depends_on: [ "baseimage" ]
    image: pelias/api
    container_name: pelias_api
    build: services/api
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "4000:4000" ]
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "libpostaldata:/usr/share/libpostal"
  interpolation:
    depends_on: [ "baseimage" ]
    image: pelias/interpolation
    container_name: pelias_interpolation
    build: services/interpolation
    restart: always
    environment: [ "PORT=4500" ]
    ports: [ "4500:4500", "21:21", "20:20" ]
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "/Users/diana/Code/interpolation:/code/pelias/interpolation"
      - "libpostaldata:/usr/share/libpostal"
      - "${DATA_DIR}:/data"
  placeholder:
    depends_on: [ "baseimage" ]
    image: pelias/placeholder
    container_name: pelias_placeholder
    build: services/placeholder
    restart: always
    environment: [ "PORT=4100" ]
    ports: [ "4100:4100" ]
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}/placeholder:/code/pelias/placeholder/data"
  pip:
    depends_on: [ "baseimage" ]
    image: pelias/pip
    container_name: pelias_pip
    build: services/pip
    restart: always
    environment: [ "PORT=4200" ]
    ports: [ "4200:4200" ]
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
#  geonames:
#    depends_on: [ "baseimage", "whosonfirst" ]
#    image: pelias/geonames
#    container_name: pelias_geonames
#    build: geonames
#    networks: [ "pelias" ]
#    volumes:
#      - "./pelias.json:/code/pelias.json"
#      - "${DATA_DIR}:/data"
#  valhalla:
#    depends_on: [ "baseimage" ]
#    image: pelias/valhalla
#    container_name: pelias_valhalla
#    build: imports/valhalla
#    restart: always
#    networks: [ "pelias" ]
#    volumes:
#      - "${DATA_DIR}:/data"
  elasticsearch:
    image: pelias/elasticsearch
    container_name: pelias_elasticsearch
    build: services/elasticsearch/2.4
    restart: always
    ports: [ "9200:9200" ]
    networks: [ "pelias" ]
    volumes:
      - "${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add: [ "IPC_LOCK" ]
